[package]
name = "dashrs"
version = "0.1.0"
authors = ["dask58 googldhruv@gmail.com"]
description = "A command-line dashboard for system stats"
repository = "https://github.com/dask-58/dashrs"

[dependencies]
crossterm = "0.25"
sysinfo = "0.28"
indicatif = "0.17"
